language: java
jdk:
  - oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - script: "mvn cobertura:cobertura"
    - stage: linter
    - script: "mvn checkstyle:check --batch-mode --fail-never"

after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2